In [1]:
import numpy as np

In [5]:
array = np.array([[0.62, 0.905, 0.525]])

In [13]:
parray = np.linalg.pinv(array)

parray

array([[0.41918799],
       [0.61187925],
       [0.35495757]])

In [11]:
np.dot(array, parray)

array([[1.]])

In [12]:
array.dot(parray)

array([[1.]])

# Check

In [ ]:
R_pi = np.array([[1, 2, 0]])