In [ ]:
import numpy as np

In [ ]:
# 配列
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])

print(data)
print('次元数: {}'.format(data.ndim))
print('要素数: {}'.format(data.size))

In [ ]:
print('掛け算: {}'.format(data**2))
print('3乗: {}'.format(data**3))
print('割り算: {}'.format(data/2))

In [ ]:
# 昇順
data.sort()
print('昇順: ', data)

#降順
data[::-1].sort()
print('降順: ',data)

# 最小値
print('最小値',data.min())

# 最大値
print('最大値', data.max())

# 合計
print('合計', data.sum())

# 積み上げ
print('積み上げ', data.cumsum())

#積み上げ割合
print('Ratio', data.cumsum()/data.sum())

# 練習

In [ ]:
l = np.array(range(10))
print(l[::1])  # 一つとび
print(l[::2])  # 二つとび

In [ ]:
l = np.random.randint(10, size = (10))
print('type l: {0}, array: {1}'.format(type(l), l))
print('type l[::1]: {0}, array: {1}'.format(type(l[::1]), l[::1] ))
print(l[::-1]) # 逆に並べる

In [ ]:
# random, 10x10
np.random.randint(2,10, size = (10,10))

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
# 一様分布の乱数生成
rand = np.random.rand(10000)                #  0.0以上、1.0未満
randint = np.random.randint(4, 10, (3, 3))  # 4以上10未満の3 x 3の配列の整数乱

# 正規分布の乱数生成
randn = np.random.randn(10000) #  平均0、分散1（標準偏差1）,  10000の乱数

In [ ]:
plt.hist(rand)

In [ ]:
# 
plt.hist(randn)

# 3週目

In [ ]:
import numpy as np

In [ ]:
data = np.array([9,2,3,4,10,6,7,8,1,5])

In [ ]:
display(data)

In [ ]:
print('次元数: ', data.ndim)

In [ ]:
print('要素数: ', data.size)

In [ ]:
data**2

In [ ]:
data**3

In [ ]:
data/2

In [ ]:
data.sort()

In [ ]:
display(data)

In [ ]:
data[::-1].sort()

In [ ]:
data

In [ ]:
data.min()

In [ ]:
data.max()

In [ ]:
data.sum()

In [ ]:
data.cumsum()/data.sum()

# 練習

In [ ]:
data[0:5]

In [ ]:
data[0:5:-1]

In [ ]:
data[0:5]

In [ ]:
data[0:5:2]

In [ ]:
data[0:5:1]

In [ ]:
data[::-1]

In [ ]:
data[0:5:-1]

In [ ]:
data[9:8:-1]

In [ ]:
data[9:6:-1]

In [ ]:
data = np.array([9,2,3,4,10,6,7,8,1,5])

In [ ]:
data

In [ ]:
data[::-1]

In [ ]:
data[::-1].sort()

In [ ]:
data

In [ ]:
data = np.array([9,2,3,4,10,6,7,8,1,5])

In [ ]:
data

In [ ]:
d = data[::-1]

In [ ]:
d

In [ ]:
d.sort()

In [ ]:
d

In [ ]:
####

In [ ]:
data = np.array([9,2,3,4,10,6,7,8,1,5])

In [ ]:
data[::-1].sort()

In [ ]:
data

In [ ]:
####

In [ ]:
data = np.array([[9,2,3,4,10,6,7,8,1,5],[9,2,3,4,33,6,7,8,1,5],[9,2,3,4,10,6,7,8,1,21]])

In [ ]:
data

In [ ]:
data.sort(axis=0)

In [ ]:
data

In [ ]:
data.sum()

In [ ]:
data.max()

In [ ]:
data.cumsum()

# 4週目

In [ ]:
import numpy as np

In [ ]:
array = np.array([9,2,3,4,10,6,7,8,1,5])

In [ ]:
display(array)
display(array.ndim)
(array.size)

In [ ]:
array**2

In [ ]:
array**3

In [ ]:
array/2

In [ ]:
array.sort()
array

In [ ]:
array[::-1].sort()

In [ ]:
array

In [ ]:
array.max()

In [ ]:
array.min()

In [ ]:
array.sum()

In [ ]:
array.cumsum()

# 5

In [1]:
import numpy as np

In [2]:
array = np.array([9,2,3,4,10,6,7,8,1,5])

In [3]:
array.ndim

1

In [4]:
array.size

10

In [5]:
array**2

array([ 81,   4,   9,  16, 100,  36,  49,  64,   1,  25])

In [9]:
array.sort()

In [10]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
array[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [12]:
array[::1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
array[::2]

array([1, 3, 5, 7, 9])

In [14]:
array[0:2:1]

array([1, 2])

In [15]:
array.min()

1

In [16]:
array.max()

10

In [17]:
array.sum()

55

In [18]:
array.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])