In [ ]:
import numpy as np

data = np.linspace(2,3,9)
display(data)

In [ ]:
# 0 - 8までの整数を発生する
data2 = np.arange(9)
display(data2)

In [ ]:
# データの準備　3x3の行列にする
array1 = data2.reshape(3,3)
display(array1)

In [ ]:
# 1行目を表示
display(array1[0, :])

In [ ]:
# 1列目を表示
display(array1[:,0])

In [ ]:
data3 = np.arange(9,18)
array2 = data3.reshape(3,3)
display(array2)

In [ ]:
# 行列の各要素の掛け算
array3 = array1*array2
display(array3)

In [ ]:
 # 行列の掛け算
array4 = np.dot(array1, array2)
display(array4)

# 3週目

In [ ]:
import numpy as np

In [ ]:
data = np.linspace(2,3,9)

In [ ]:
data

In [ ]:
data = np.arange(9)

In [ ]:
array = data.reshape(3,3)
display(array)

In [ ]:
array[0,:]

In [ ]:
array[:,0]

In [ ]:
array2 = np.arange(9,18)

In [ ]:
array2 = array2.reshape(3,3)

In [ ]:
np.dot(array, array2)

# 4週目

In [ ]:
import numpy as np

In [ ]:
np.linspace(2,3,9)

In [ ]:
array1 = np.arange(9)

In [ ]:
array1 = array1.reshape(3,3)
array1

In [ ]:
array1[0,:]

In [ ]:
array1[:,0]

In [ ]:
array2 = np.arange(9, 18).reshape(3,3)
array2

In [ ]:
array1*array2

In [ ]:
array1.dot(array2)

# 5

In [1]:
import numpy as np

In [2]:
np.linspace(2,3,9)

array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ])

In [4]:
np.linspace(0,8,9)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [8]:
array_ = np.arange(9).reshape(3,3)

In [9]:
array_

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
array_[0,:]

array([0, 1, 2])

In [11]:
array_[:,0]

array([0, 3, 6])

In [12]:
array2 = np.arange(9, 18).reshape(3,3)

In [13]:
array2

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])