# 2週目
algebra : 代数  

eigenvalue : 固有値

In [ ]:
import numpy as np
import scipy.linalg as linalg

In [ ]:
matrix = np.array([[1,-1,-1], [-1,1,-1],[-1,-1,1]])

In [ ]:
# 行列式
display('行列式', linalg.det(matrix))

In [ ]:
# 逆行列
display('逆行列', linalg.inv(matrix))

In [ ]:
# 行列の積
display(matrix.dot(linalg.inv(matrix)))

In [ ]:
#　固有値(eigenvalue)と固有ベクトル(eigenvector)
eig_val, eig_vec = linalg.eig(matrix)
display('固有値' , eig_val)
display('固有ベクトル', eig_vec)

# 3週目

In [ ]:
import scipy as sp
import numpy as np

In [ ]:
array = np.array([[1,-1,-1],[-1,1,-1],[-1,-1,1]])

In [ ]:
array

In [ ]:
np.linalg.det(array)

In [ ]:
array_inv = np.linalg.inv(array)

In [ ]:
np.dot(array, array_inv)

In [ ]:
eig_value, eig_vector = np.linalg.eig(array)

# 4週目

In [ ]:
import numpy as np

In [ ]:
array = np.array([1,-1,-1,-1,1,-1,-1,-1,1]).reshape(3,3)

In [ ]:
array

In [ ]:
import scipy as sp
import scipy.linalg as linalg

In [ ]:
sp.linalg.det(array)

In [ ]:
sp.linalg.inv(array)

In [ ]:
sp.linalg.eigvals(array)

In [ ]:
evalu, evec = sp.linalg.eig(array)

In [ ]:
evalu

In [ ]:
evec

# 5

In [2]:
import numpy as np

In [3]:
array = np.array([1, -1, -1, -1, 1, -1, -1, -1, 1]).reshape(3,3)

In [4]:
array

array([[ 1, -1, -1],
       [-1,  1, -1],
       [-1, -1,  1]])

In [22]:
np.linalg.det(array)

-4.0

In [23]:
import scipy.linalg as linalg
linalg.det(array)

-4.0

In [21]:
array2 = np.linalg.inv(array)
array2

array([[ 0. , -0.5, -0.5],
       [-0.5, -0. , -0.5],
       [-0.5, -0.5, -0. ]])

In [12]:
array3 = array.dot(array2)
array3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
import scipy as sp
import scipy.linalg as linalg

In [18]:
val, vec = linalg.eig(array)

In [19]:
val

array([-1.+0.j,  2.+0.j,  2.+0.j])

In [20]:
vec

array([[ 0.57735027, -0.81649658,  0.42755853],
       [ 0.57735027,  0.40824829, -0.81618716],
       [ 0.57735027,  0.40824829,  0.38862863]])