In [27]:
import numpy as np

data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])

In [28]:
print(data)
print('次元数:', data.ndim)
print('要素数:', data.size)

[ 9  2  3  4 10  6  7  8  1  5]
次元数: 1
要素数: 10


In [29]:
print('掛け算:', data*data)
print('塁乗:', np.power(data,3))
print('割り算:', data/2)

掛け算: [ 81   4   9  16 100  36  49  64   1  25]
塁乗: [ 729    8   27   64 1000  216  343  512    1  125]
割り算: [4.5 1.  1.5 2.  5.  3.  3.5 4.  0.5 2.5]


In [30]:
print('昇順:', np.sort(data))

昇順: [ 1  2  3  4  5  6  7  8  9 10]


In [33]:
print('降順', np.sort(data)[::-1])
print('slice', data[0:5:2])

data2 = np.array([[9, 2, 3, 4, 10, 6, 7, 8, 1, 5],[1,2,3,4,5,6,7,8,9,10]])
print('data2: ', data2)
print('data2 次元反転',data2[::-1])

降順 [10  9  8  7  6  5  4  3  2  1]
slice [ 9  3 10]
data2:  [[ 9  2  3  4 10  6  7  8  1  5]
 [ 1  2  3  4  5  6  7  8  9 10]]
data2 次元反転 [[ 1  2  3  4  5  6  7  8  9 10]
 [ 9  2  3  4 10  6  7  8  1  5]]


In [38]:
print('Min: ', np.amin(data))
print('Min Index: ', np.argmin(data))
data

Min:  1
Min Index:  8


array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [40]:
print('Max: ', np.amax(data))
print('Max Index: ', np.argmax(data))

Max:  10
Max Index:  4


In [42]:
print('Sum: ', np.sum(data))
print('Sum: ', data.sum())

Sum:  55
Sum:  55


In [43]:
dOrder = np.sort(data)[::-1]
print('Cum: ', dOrder.cumsum())

Cum:  [10 19 27 34 40 45 49 52 54 55]


In [45]:
Sum = data.sum()
print('Ratio:', dOrder.cumsum()/Sum)

Ratio: [0.18181818 0.34545455 0.49090909 0.61818182 0.72727273 0.81818182
 0.89090909 0.94545455 0.98181818 1.        ]
