In [3]:
import numpy as np

array = np.linspace(2,3,9)
display(array)

array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ])

In [6]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
array1 = np.arange(9).reshape(3,3)
display(array1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
display(array1[0,:])

array([0, 1, 2])

In [16]:
display(array1[:,0])

array([0, 3, 6])

In [20]:
array2 = np.arange(9,18).reshape(3,3)
display(array2)

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [21]:
print(array1*array2)

[[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]


In [22]:
print(array1.dot(array2))

[[ 42  45  48]
 [150 162 174]
 [258 279 300]]
