In [3]:
import numpy as np
import scipy.linalg as linalg

In [6]:
matrix = np.array([[1,-1,-1],[-1,1,-1],[-1, -1, 1]])
display(matrix)

array([[ 1, -1, -1],
       [-1,  1, -1],
       [-1, -1,  1]])

In [7]:
display('行列式')
linalg.det(matrix)

'行列式'

-4.0

In [8]:
display('逆行列')
linalg.inv(matrix)

'逆行列'

array([[ 0. , -0.5, -0.5],
       [-0.5, -0. , -0.5],
       [-0.5, -0.5,  0. ]])

In [12]:
eig_val, eig_vector = linalg.eig(matrix)
display('固有値')
display(eig_val)
display('固有ベクトル')
display(eig_vector)

'固有値'

array([-1.+0.j,  2.+0.j,  2.+0.j])

'固有ベクトル'

array([[ 0.57735027, -0.81649658,  0.42755853],
       [ 0.57735027,  0.40824829, -0.81618716],
       [ 0.57735027,  0.40824829,  0.38862863]])

In [19]:
display('内積')
display(eig_vector[:,0]*eig_vector[:,1])
display(np.inner(eig_vector[:,0], eig_vector[:,1]))

'内積'

array([-0.47140452,  0.23570226,  0.23570226])

-1.3877787807814457e-16